version: "3.8"
services:
  access-key-checker:
    image: ${IMAGE}
    ports:
      - "8080:8080"
    command: ["flask", "run", "--host=0.0.0.0", "--port=8080"]
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}